package com.fedex.geopolitical.constants;

public enum JmsDataSegment {

	SCRIPT, UOM, LANGUAGE, DAY_OF_WEEK, MONTH_OF_YEAR, COUNTRY, STATE_PROV_STD, COUNTRY_ORG_STD, GEOPL_RELATIONSHIP, GEOPL_TYPE, GEOPL_RELATIONSHIP_TYPE, GEOPL_AFFIL_TYPE, GEOPL_ORG_STD, HOLIDAY, DEPN_CNTRY_RLTSP,

}
